[package]
name = "onenote_parser"
version = "0.0.1"
authors = ["Pedro Luiz <pedrlz.frn@gmail.com>"]
edition = "2024"
description = "Parse Microsoft OneNoteÂ® notebooks"
license = "MPL-2.0-no-copyleft-exception"
repository = "https://github.com/laurent22/joplin"
keywords = ["onenote"]

[features]
backtrace = []

[dependencies]
bytes = "1.11"
encoding_rs = "0.8"
enum-primitive-derive = "0.3"
itertools = "0.14"
log = "0.4"
num-traits = "0.2"
sanitise-file-name = "1.0"
thiserror = "2.0"
uuid = "1.19"
widestring = "1.2"

onenote_parser_macros = { path = "../onenote_parser_macros" }
parser-utils = { path = "../parser-utils" }

[dev-dependencies]
insta = "1.45"
tempfile = "3.15"
yare = "3.0.0"


[dependencies.web-sys]
version = "0.3"
features = [
    "console"
]

[lib]
crate-type = ["cdylib", "lib"]
